### PR TITLE
Auto Update - Windows Agent

### PR DESCRIPTION
**Pull request by Adjokip**
Added the auto-update functions for the Windows agent.

Haven't been able to test as I do not have a Windows VM up at the moment. However, I believe it should work on Windows, as it does on Linux - and there's nothing too OS centric.

### CODE REVIEW

**Comment by own3mall** [comment]
Can you please test this on Windows before I merge?  There are subtle differences that could come back to haunt us.  

I'll try to test if I get a moment too, but we'll see.

**Comment by Adjokip** [comment]
I just tested. Seems to work fine.

Also tested the core assignment in Windows. Works too. Need to commit a small change for Windows specific in that, however.

**Comment by Adjokip** [comment]
One thing that seems to be different from the Linux agent is the `fetch_steam_version` method.

Getting the Steam version works on the Linux agent. It works on Windows too, if you execute the command via the command line. But it doesn't work correctly when `fetch_steam_version` is called by the Windows agent - the output gets as far as:

```
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
```

I don't really know what the cause of that may be, as it works when executing it from the command line.

**Comment by Adjokip** [comment]
For the comment I made above, it doesn't seem to be an issue with `fetch_steam_version` on the Windows agent side... but how perl is executing stuff, or how stuff is being passed back to perl.

The output in my previous comment was from TF2's AppID and was incomplete. However if it was executed manually via the command line, it would show the full, expected output. The command would be:

```
/OGP/steamcmd/steamcmd.exe +login anonymous +app_info_update 1 +app_info_print 232250 +quit
```

It doesn't seem to be anything specific to the agent that causes the output to be cut off. If I create a new script with the following, it saves to `app_update.log` the same as what the `fetch_steam_version` function from the agent returns.

```perl
#!/usr/bin/perl

use warnings;
use strict;

system("/OGP/steamcmd/steamcmd.exe +login anonymous +app_info_update 1 +app_info_print 232250 +quit >/OGP/steamcmd/app_update.log 2>&1");
```

Other AppID's may return more content, but the few I tried were typically missing between 5-10 lines, compared to the output you'd get if you had ran the command from the terminal.

This issue only happens when on the Windows agent and the command  is sent by perl.

Really don't know why. I've not used perl much... but, considering each AppID always has the same data returned per execution (that is, TF2's AppID doesn't get to the important data, Ark fails around 8 lines from the bottom compared to running the command in the command line), it seems maybe the problem is how data is being passed back to perl - for what reason, I'm not sure.

**Comment by own3mall** [comment]
I'll take a look soon.  Thanks for your work on this.

**Comment by own3mall** [comment]
Merging this in for now.  It will make my life easier for debugging.  I'll see if I can't fix that issue shortly.

**Comment by own3mall** [comment]
This is known issue on Windows:

https://github.com/ValveSoftware/Source-1-Games/issues/1929

Not sure how to work around it.

**Comment by own3mall** [comment]
We can use this instead?

https://developer.valvesoftware.com/wiki/Steam_Web_API#JSON

GetSchemaForGame returns gamename, gameversion and availablegamestats(achievements and stats).

Example URL: http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?key=XXXXXXXXXXXXXXXXX&appid=218620

**Comment by Adjokip** [comment]
Doesn't seem like it, that API method doesn't return anything for server AppID's.

If you instead pass a normal game AppID to it (TF2 is 440, the server is 232250) you get output, but it's not in the same format we require it to be. steamapps/appmanifest_id.acf only contains the build id, this call contains a version.

**Comment by own3mall** [comment]
Can't we grep the build?

**Comment by own3mall** [comment]
I'll write something in python that will run steamcmd and parse the output and then be accessible from opengamepanel.org

**Comment by Adjokip** [comment]
`installed_steam_version` greps the buildid from steamapps/appmanifest_appid.acf, which is the currently installed version. And it works, but we need to get the latest buildid info too.

`fetch_steam_version` is suppose to get the latest buildid and then return the value after using grep on it. They'll both use grep if the last argument was 0, if it's 1, it returns the output without any grepping.

But due to the output being incomplete, `fetch_steam_version` can't do much currently.

**Comment by own3mall** [comment]
Use this new API for Windows:

http://opengamepanel.org/supported_games/api.php?appid=294420&action=getBuildId

Adjust appid accordingly to what we need... this is pulled from a Linux server, so I hope that won't cause issues with OS type.

You may need to add a timeout to this http call in PERL since the script itself may take up to 10 seconds to the get buildID if it's not cached or out-of-date.

NOTE, the build id may be out of sync for up to 10 minutes after it changes due to caching used on the API to prevent abuse.

**Comment by Adjokip** [comment]
Thanks!

PR submitted. #2

**Pull request merged**
